pipeline {
  agent any

  options {
    timestamps()
    disableConcurrentBuilds()
  }

  environment {
    PYTEST_REPORT = "messaging_app/reports/pytest-report.xml"
  }

  stages {
    stage('Checkout') {
      steps {
        git branch: 'main',
            credentialsId: 'github-creds',
            url: 'https://github.com/TAREK-1988/alx-backend-python.git'
      }
    }

    stage('Install dependencies') {
      steps {
        sh '''
          set -e
          mkdir -p messaging_app/reports
          python3 --version
          pip3 --version
          pip3 install --upgrade pip
          pip3 install -r messaging_app/requirements.txt
          pip3 install pytest pytest-django
        '''
      }
    }

    stage('Run tests') {
      steps {
        sh '''
          set -e
          pytest -q messaging_app --junitxml=messaging_app/reports/pytest-report.xml
        '''
      }
    }
  }

  post {
    always {
      junit allowEmptyResults: true, testResults: "messaging_app/reports/pytest-report.xml"
      archiveArtifacts allowEmptyArchive: true, artifacts: "messaging_app/reports/**"
    }
  }
}
